version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/go/src/github.com/alizoubair/greenlight
    container_name: greenlight
    environment:
      - GREENLIGHT_DB_DSN=${GREENLIGHT_DB_DSN}
    restart: always
    ports:
      - 4000:4000
    tty: true
    depends_on:
      - db
    networks:
      - fullstack
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: "greenlight"
    ports:
      - 5432:5432
    networks:
      - fullstack
networks:
  fullstack:
    driver: bridge